apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        ports:
        - containerPort: 80
        env:
        - name: PMA_HOST
          value: rc1a-eiayqmru78vvuq1l.mdb.yandexcloud.net
        - name: PMA_PORT
          value: "3306"
        - name: PMA_USER
          value: "elfxf"
        - name: PMA_PASSWORD
          value: "12345elfxf"
        - name: PMA_PMADB
          value: netology_db
