---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu_latest
    image: docker.io/pycontribs/ubuntu:latest
    pre_build_image: true
  - name: oracle_linux
    image: docker.io/pycontribs/oraclelinux:8
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
