{
 "title": "Local monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Утилизация CPU (в процентах, 100-idle)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - avg(irate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\"}[1m])) * 100",
     "legendFormat": "Утилизация CPU (в процентах, 100-idle)"
    }
   ]
  },
  {
   "title": "Средняя нагрузка на процессор",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "avg(node_load1{job=\"node-exporter\"})",
     "legendFormat": "Средняя нагрузка на процессор за последнюю 1 минуту"
    },
    {
     "expr": "avg(node_load5{job=\"node-exporter\"})",
     "legendFormat": "Средняя нагрузка на процессор за последние 5 минут"
    },
    {
     "expr": "avg(node_load15{job=\"node-exporter\"})",
     "legendFormat": "Средняя нагрузка на процессор за последние 15 минут"
    }
   ]
  },
  {
   "title": "Оперативная память",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes",
     "legendFormat": "Общее количество оперативной памяти"
    },
    {
     "expr": "node_memory_MemFree_bytes",
     "legendFormat": "Количество свободной  оперативной памяти"
    }
   ]
  },
  {
   "title": "Количество места на файловой системе",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_filesystem_avail_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}